# Form implementation generated from reading ui file 'ui/dialog_add_florder.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(300, 350))
        Dialog.setStyleSheet("background-color: rgb(179, 254, 188);\n"
"color: rgb(0, 0, 0);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.quan_lab = QtWidgets.QLabel(parent=Dialog)
        self.quan_lab.setObjectName("quan_lab")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.quan_lab)
        self.price_lab = QtWidgets.QLabel(parent=Dialog)
        self.price_lab.setObjectName("price_lab")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.price_lab)
        self.lineEdit_orice = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_orice.setObjectName("lineEdit_orice")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_orice)
        self.buy_label = QtWidgets.QLabel(parent=Dialog)
        self.buy_label.setObjectName("buy_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.buy_label)
        self.comboBox_buy = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_buy.setObjectName("comboBox_buy")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_buy)
        self.spinBox_quan = QtWidgets.QSpinBox(parent=Dialog)
        self.spinBox_quan.setObjectName("spinBox_quan")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox_quan)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton_order_buy = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_order_buy.setFont(font)
        self.pushButton_order_buy.setStyleSheet("background-color: rgb(136, 192, 142);")
        self.pushButton_order_buy.setObjectName("pushButton_order_buy")
        self.verticalLayout.addWidget(self.pushButton_order_buy)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.quan_lab.setText(_translate("Dialog", "Сколько?"))
        self.price_lab.setText(_translate("Dialog", "Стоимость:"))
        self.buy_label.setText(_translate("Dialog", "Что покупаем?"))
        self.pushButton_order_buy.setText(_translate("Dialog", "Заказать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
